use crate::checks::CheckStatus;
use crate::util::*;
use anyhow::Result;
use std::fs;

// -------------------------------------------------------
// Shared: build a package from an embedded, known-good PKGBUILD.
//
// These PKGBUILDs are frozen copies of ones proven to build cleanly with
// systemd support stripped out — not fetched live from AUR — so this
// never depends on an upstream maintainer's file matching a pattern we
// expect to sed against. If upstream changes meaningfully, this needs a
// manual update, but it can never silently break from a format change.
// -------------------------------------------------------
fn build_from_embedded_pkgbuild(pkg_dir_name: &str, pkgbuild: &str) -> Result<()> {
    let home = real_home()?;
    let build_root = home.join(".cache/distro-tool/build").join(pkg_dir_name);
    fs::create_dir_all(&build_root)?;
    fs::write(build_root.join("PKGBUILD"), pkgbuild)?;

    // makepkg refuses to run as root, and must run as the real user —
    // this tool is expected to be invoked without sudo, with individual
    // privileged steps (pacman -S, mv into /etc, etc.) using sudo
    // internally where needed.
    let build = run_in(&build_root, "makepkg", &["--noconfirm", "-si"])?;
    if !build.status.success() {
        anyhow::bail!(
            "build failed: {}",
            String::from_utf8_lossy(&build.stderr).trim()
        );
    }
    Ok(())
}

// -------------------------------------------------------
// irqbalance — the AUR git package links against libsystemd by default
// (for sd_notify support, which dinit doesn't need). Built here with
// -Dsystemd=disabled, matching what we proved working.
// -------------------------------------------------------
const IRQBALANCE_PKGBUILD: &str = r#"
pkgname=irqbalance-git
pkgver=1.9.5.rDISTROTOOL
pkgrel=1
pkgdesc="A daemon to help balance the CPU load generated by interrupts across all of a systems CPUs (dinit build, systemd disabled)"
arch=('x86_64')
url="https://irqbalance.github.io/irqbalance/"
license=('GPL-2.0-or-later')
depends=('glibc' 'libcap-ng.so' 'libglib-2.0.so' 'libncursesw.so' 'libnl' 'libnuma.so')
makedepends=('git' 'meson' 'glib2' 'libcap-ng' 'ncurses' 'systemd')
provides=("irqbalance=$pkgver")
conflicts=('irqbalance')
source=("git+https://github.com/Irqbalance/irqbalance.git")
sha256sums=('SKIP')

pkgver() {
  cd "irqbalance"
  git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd "irqbalance"
  meson setup \
    --buildtype=plain \
    --prefix="/usr" \
    --sbindir="bin" \
    -Ddefault_library="both" \
    -Dsystemd=disabled \
    "_build"
  meson compile -C "_build"
}

package() {
  cd "irqbalance"
  meson install -C "_build" --destdir "$pkgdir"
  mv "$pkgdir/usr/etc" "$pkgdir/etc" 2>/dev/null || true
}
"#;

pub fn check_irqbalance(apply: bool) -> Result<CheckStatus> {
    let binary = "/usr/bin/irqbalance";
    let installed_clean =
        std::path::Path::new(binary).exists() && !linked_against_systemd(binary);
    let running = dinit_boot_enabled("irqbalance");

    if installed_clean && running {
        return Ok(CheckStatus::Ok(
            "irqbalance is installed (systemd-free build) and running".to_string(),
        ));
    }

    let problem = if !std::path::Path::new(binary).exists() {
        "irqbalance is not installed".to_string()
    } else if linked_against_systemd(binary) {
        "irqbalance is installed but linked against systemd — needs a clean rebuild".to_string()
    } else {
        "irqbalance is installed but not running at boot".to_string()
    };

    if !apply {
        return Ok(CheckStatus::NeedsAttention(problem));
    }

    if !installed_clean {
        if package_installed("irqbalance-git") {
            let _ = run("sudo", &["pacman", "-Rns", "--noconfirm", "irqbalance-git"]);
        }
        if let Err(e) = build_from_embedded_pkgbuild("irqbalance-git", IRQBALANCE_PKGBUILD) {
            return Ok(CheckStatus::NeedsAttention(format!("{problem} — {e}")));
        }
    }

    let service = "type = process\ncommand = /usr/bin/irqbalance --foreground\nrestart = true\n";
    write_privileged_file("/etc/dinit.d/irqbalance", service)?;
    dinit_enable("irqbalance")?;
    dinit_start("irqbalance")?;

    Ok(CheckStatus::Fixed(format!(
        "{problem} — built clean and started (systemd support disabled)"
    )))
}

// -------------------------------------------------------
// ananicy-cpp — no -dinit companion package exists on Artix, and the
// stock Arch/CachyOS build links against systemd. Built here with
// -DENABLE_SYSTEMD=OFF, plus the unistd.h patch newer GCC requires
// (getpid() used without the header that declares it).
// -------------------------------------------------------
const ANANICY_CPP_PKGBUILD: &str = r#"
pkgname=ananicy-cpp
pkgver=1.2.0
pkgrel=1
pkgdesc="Ananicy rewritten in C++ for much lower CPU and memory usage (systemd support disabled)"
arch=('x86_64')
url="https://gitlab.com/ananicy-cpp/ananicy-cpp"
license=('GPL-3.0-or-later')
depends=('zlib' 'gcc-libs' 'glibc')
makedepends=('cmake' 'ninja' 'clang' 'git' 'nlohmann-json')
provides=('ananicy-cpp')
conflicts=('ananicy-cpp')
source=("git+https://gitlab.com/ananicy-cpp/ananicy-cpp.git#tag=v${pkgver}")
sha256sums=('SKIP')

prepare() {
  cd "ananicy-cpp"
  sed -i '1i #include <unistd.h>' src/platform/linux/debug.cpp
  sed -i '1i #include <unistd.h>' src/platform/linux/process.cpp
}

build() {
  cd "ananicy-cpp"
  cmake -B build \
    -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_SYSTEMD=OFF \
    -DVERSION="${pkgver}" \
    -S .
  cmake --build build --target ananicy-cpp
}

package() {
  cd "ananicy-cpp"
  DESTDIR="${pkgdir}" cmake --install build --component Runtime
}
"#;

pub fn check_ananicy_cpp(apply: bool) -> Result<CheckStatus> {
    let binary = "/usr/bin/ananicy-cpp";
    let installed_clean =
        std::path::Path::new(binary).exists() && !linked_against_systemd(binary);
    let running = dinit_boot_enabled("ananicy-cpp");

    if installed_clean && running {
        return Ok(CheckStatus::Ok(
            "ananicy-cpp is installed (systemd-free build) and running".to_string(),
        ));
    }

    let problem = if !std::path::Path::new(binary).exists() {
        "ananicy-cpp is not installed".to_string()
    } else if linked_against_systemd(binary) {
        "ananicy-cpp is installed but linked against systemd — needs a clean rebuild".to_string()
    } else {
        "ananicy-cpp is installed but not running at boot".to_string()
    };

    if !apply {
        return Ok(CheckStatus::NeedsAttention(problem));
    }

    if !installed_clean {
        // The rules package depends on ananicy-cpp, so it has to come out
        // first — then goes back in afterward, it's not itself a problem.
        let had_rules = package_installed("cachyos-ananicy-rules-git");
        if package_installed("ananicy-cpp") {
            let mut remove_args = vec!["pacman", "-Rns", "--noconfirm", "ananicy-cpp"];
            if had_rules {
                remove_args.push("cachyos-ananicy-rules-git");
            }
            let _ = run("sudo", &remove_args);
        }
        if let Err(e) = build_from_embedded_pkgbuild("ananicy-cpp", ANANICY_CPP_PKGBUILD) {
            return Ok(CheckStatus::NeedsAttention(format!("{problem} — {e}")));
        }
        if had_rules {
            let _ = run("sudo", &["pacman", "-S", "--needed", "--noconfirm", "cachyos-ananicy-rules-git"]);
        }
    }

    let service = "type = process\ncommand = /usr/bin/ananicy-cpp start\nrestart = true\n";
    write_privileged_file("/etc/dinit.d/ananicy-cpp", service)?;
    dinit_enable("ananicy-cpp")?;
    dinit_start("ananicy-cpp")?;

    Ok(CheckStatus::Fixed(format!(
        "{problem} — built clean and started (systemd support disabled)"
    )))
}

// -------------------------------------------------------
// auto-cpufreq — installs fine from the repo, but its own dinit
// installer script is broken in this package build (missing file it
// tries to copy), and it conflicts with power-profiles-daemon.
// -------------------------------------------------------
pub fn check_auto_cpufreq(apply: bool) -> Result<CheckStatus> {
    let installed = package_installed("auto-cpufreq");
    let running = dinit_boot_enabled("auto-cpufreq");
    let ppd_conflict = dinit_boot_enabled("power-profiles-daemon");

    if installed && running && !ppd_conflict {
        return Ok(CheckStatus::Ok(
            "auto-cpufreq is installed and running".to_string(),
        ));
    }

    let mut problems = Vec::new();
    if !installed {
        problems.push("not installed");
    }
    if installed && !running {
        problems.push("not running at boot");
    }
    if ppd_conflict {
        problems.push("power-profiles-daemon is also enabled and will conflict with it");
    }
    let problem = format!("auto-cpufreq: {}", problems.join(", "));

    if !apply {
        return Ok(CheckStatus::NeedsAttention(problem));
    }

    if !installed {
        let install = run("sudo", &["pacman", "-S", "--needed", "--noconfirm", "auto-cpufreq"])?;
        if !install.status.success() {
            return Ok(CheckStatus::NeedsAttention(format!(
                "{problem} — install failed: {}",
                String::from_utf8_lossy(&install.stderr).trim()
            )));
        }
    }

    if ppd_conflict {
        dinit_disable("power-profiles-daemon")?;
    }

    let service = "type = process\ncommand = /usr/bin/auto-cpufreq --daemon\nrestart = true\n";
    write_privileged_file("/etc/dinit.d/auto-cpufreq", service)?;
    dinit_enable("auto-cpufreq")?;
    dinit_start("auto-cpufreq")?;

    Ok(CheckStatus::Fixed(format!(
        "{problem} — resolved and running"
    )))
}

pub fn all_tuning_checks() -> Vec<(&'static str, fn(bool) -> Result<CheckStatus>)> {
    vec![
        ("CPU frequency scaling (auto-cpufreq)", check_auto_cpufreq),
        ("IRQ balancing (irqbalance)", check_irqbalance),
        ("Process priority tuning (ananicy-cpp)", check_ananicy_cpp),
    ]
}
